/**
 * ESG360 — Comprehensive Seed Script
 * Populates complete, realistic dummy data for:
 * - 4-Tier Organization Hierarchy (Group -> Subsidiary -> Business Unit -> Project)
 * - Users with all 10 standard roles
 * - Comprehensive ESG Records across Environmental, Social, and Governance for 2026, 2025, and 2024
 * - BRSR Reports with section progress
 * - Notifications & Compliance Audit Logs
 *
 * Run: node seed.js
 */

require('dotenv').config();
const mongoose = require('mongoose');
const {
  User,
  Organization,
  ESGData,
  BRSRReport,
  Document,
  Notification,
  AuditLog,
} = require('./models');

const ADMIN_PASSWORD = 'Admin@123456';

async function seed() {
  console.log('🌱 Connecting to MongoDB Atlas...');
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✅ Connected to MongoDB\n');

  console.log('🧹 Clearing existing demo data...');
  await Promise.all([
    User.deleteMany({}),
    Organization.deleteMany({}),
    ESGData.deleteMany({}),
    BRSRReport.deleteMany({}),
    Document.deleteMany({}),
    Notification.deleteMany({}),
    AuditLog.deleteMany({}),
  ]);
  console.log('✅ Clean slate prepared.\n');

  // 1. CREATE ORGANIZATIONS HIERARCHY
  console.log('🏢 Creating 4-Tier Organization Structure...');

  // Level 1: Root Group
  const groupOrg = await Organization.create({
    name: 'ESG360 Infra Group Ltd.',
    type: 'Group',
    location: {
      address: 'ESG360 Towers, Bandra Kurla Complex',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400051',
    },
    cin: 'L45200MH2012PLC234567',
    gstin: '27AABCE1234F1Z5',
    industry: 'Infrastructure & Renewable Energy',
    description: 'Conglomerate operating across clean energy, freight logistics, and urban transport infrastructure.',
    status: 'Active',
    reportingYear: '2026',
  });

  // Level 2: Subsidiaries
  const cleanEnergySub = await Organization.create({
    name: 'ESG360 Clean Energy Ltd.',
    type: 'Subsidiary',
    parent: groupOrg._id,
    location: {
      address: 'Solarium Park, SG Highway',
      city: 'Ahmedabad',
      state: 'Gujarat',
      country: 'India',
      pincode: '380054',
    },
    cin: 'U40106GJ2015PLC081234',
    industry: 'Solar & Wind Power Generation',
    status: 'Active',
    reportingYear: '2026',
  });

  const logisticsSub = await Organization.create({
    name: 'ESG360 Logistics & Freight Ltd.',
    type: 'Subsidiary',
    parent: groupOrg._id,
    location: {
      address: 'Port Logistics Park, Harbour Expressway',
      city: 'Chennai',
      state: 'Tamil Nadu',
      country: 'India',
      pincode: '600001',
    },
    cin: 'U60200TN2016PLC091823',
    industry: 'Freight Rail & Port Terminals',
    status: 'Active',
    reportingYear: '2026',
  });

  const urbanInfraSub = await Organization.create({
    name: 'ESG360 Urban Infrastructure Ltd.',
    type: 'Subsidiary',
    parent: groupOrg._id,
    location: {
      address: 'Metro Hub, Outer Ring Road',
      city: 'Bengaluru',
      state: 'Karnataka',
      country: 'India',
      pincode: '560103',
    },
    cin: 'U45203KA2017PLC102938',
    industry: 'Urban Mobility & Highway EPC',
    status: 'Active',
    reportingYear: '2026',
  });

  // Level 3: Business Units
  const solarBU = await Organization.create({
    name: 'Solar Parks Business Unit',
    type: 'Business Unit',
    parent: cleanEnergySub._id,
    location: { city: 'Jodhpur', state: 'Rajasthan' },
    industry: 'Utility Scale Solar',
    status: 'Active',
    reportingYear: '2026',
  });

  const windBU = await Organization.create({
    name: 'Wind & Hybrid Systems BU',
    type: 'Business Unit',
    parent: cleanEnergySub._id,
    location: { city: 'Bhuj', state: 'Gujarat' },
    industry: 'Wind & BESS Hybrid Power',
    status: 'Active',
    reportingYear: '2026',
  });

  const coldChainBU = await Organization.create({
    name: 'Cold Chain & Warehouse BU',
    type: 'Business Unit',
    parent: logisticsSub._id,
    location: { city: 'Nagpur', state: 'Maharashtra' },
    industry: 'Cold Storage & Intermodal Warehousing',
    status: 'Active',
    reportingYear: '2026',
  });

  const highwaysBU = await Organization.create({
    name: 'Highways & Bridges BU',
    type: 'Business Unit',
    parent: urbanInfraSub._id,
    location: { city: 'Hyderabad', state: 'Telangana' },
    industry: 'Expressway EPC',
    status: 'Active',
    reportingYear: '2026',
  });

  // Level 4: Projects / Operating Facilities
  const bhadlaProject = await Organization.create({
    name: 'Bhadla 500MW Ultra Solar Park',
    type: 'Project',
    parent: solarBU._id,
    location: { city: 'Bhadla', state: 'Rajasthan' },
    industry: 'Solar Generation Plant',
    status: 'Active',
    reportingYear: '2026',
  });

  const khavdaProject = await Organization.create({
    name: 'Khavda 1GW Hybrid Site',
    type: 'Project',
    parent: windBU._id,
    location: { city: 'Khavda', state: 'Gujarat' },
    industry: 'Hybrid Wind & Solar Site',
    status: 'Active',
    reportingYear: '2026',
  });

  const freightTerminal = await Organization.create({
    name: 'Western Dedicated Freight Hub',
    type: 'Project',
    parent: coldChainBU._id,
    location: { city: 'Vadodara', state: 'Gujarat' },
    industry: 'Intermodal Freight Yard',
    status: 'Active',
    reportingYear: '2026',
  });

  const metroProject = await Organization.create({
    name: 'Metro Line 3 Civil Package',
    type: 'Project',
    parent: highwaysBU._id,
    location: { city: 'Pune', state: 'Maharashtra' },
    industry: 'Mass Rapid Transit Infrastructure',
    status: 'Active',
    reportingYear: '2026',
  });

  console.log('✅ Created 12 Organizations across 4 tiers.\n');

  // 2. CREATE USERS ACROSS ROLES
  console.log('👥 Creating Demo Users across all roles...');
  const usersToCreate = [
    {
      name: 'Super Admin',
      email: 'admin@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Super Admin',
      organization: groupOrg._id,
      department: 'Executive Governance',
    },
    {
      name: 'Group ESG Director',
      email: 'group.admin@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Group ESG Admin',
      organization: groupOrg._id,
      department: 'Group ESG & Sustainability',
    },
    {
      name: 'Clean Energy Admin',
      email: 'energy.sub@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Subsidiary Admin',
      organization: cleanEnergySub._id,
      department: 'Operations & Sustainability',
    },
    {
      name: 'Logistics Admin',
      email: 'logistics.sub@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Subsidiary Admin',
      organization: logisticsSub._id,
      department: 'Logistics Compliance',
    },
    {
      name: 'Solar BU Manager',
      email: 'solar.bu@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Business Unit Manager',
      organization: solarBU._id,
      department: 'Renewable Power Ops',
    },
    {
      name: 'Bhadla Facility Engineer',
      email: 'bhadla.user@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Project/Department User',
      organization: bhadlaProject._id,
      department: 'Plant Operations & Data Entry',
    },
    {
      name: 'Priya Sharma (ESG Manager)',
      email: 'esg.manager@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'ESG Manager',
      organization: groupOrg._id,
      department: 'Corporate Sustainability',
    },
    {
      name: 'Rajesh Verma (Compliance Officer)',
      email: 'compliance@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Compliance Officer',
      organization: groupOrg._id,
      department: 'Legal & SEBI Compliance',
    },
    {
      name: 'KPMG Lead Reviewer',
      email: 'auditor@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Auditor/Reviewer',
      organization: groupOrg._id,
      department: 'External ESG Assurance',
    },
    {
      name: 'Managing Director (Board)',
      email: 'mgmt@esg360.com',
      password: ADMIN_PASSWORD,
      role: 'Management',
      organization: groupOrg._id,
      department: 'Board of Directors',
    },
  ];

  const createdUsers = [];
  for (const u of usersToCreate) {
    const user = await User.create(u);
    createdUsers.push(user);
  }

  const superAdmin = createdUsers[0];
  const esgManager = createdUsers[6];
  const complianceOfficer = createdUsers[7];
  const plantUser = createdUsers[5];

  // Link admin users to orgs
  await Organization.updateOne({ _id: groupOrg._id }, { adminUser: superAdmin._id });
  await Organization.updateOne({ _id: cleanEnergySub._id }, { adminUser: createdUsers[2]._id });
  await Organization.updateOne({ _id: logisticsSub._id }, { adminUser: createdUsers[3]._id });

  console.log(`✅ Created ${createdUsers.length} Users.\n`);

  // 3. CREATE COMPREHENSIVE ESG DATA
  console.log('📊 Seeding Rich ESG Records (Environmental, Social, Governance)...');

  const esgRecords = [
    // ══════════════════════════════════════════════════════
    // YEAR 2026 (CURRENT REPORTING PERIOD)
    // ══════════════════════════════════════════════════════

    // ENVIRONMENTAL (2026)
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Total Energy Consumption',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 185400,
      unit: 'GJ',
      description: 'Total direct and indirect energy consumption across all clean energy facilities.',
      dataSource: 'SCADA Energy Meters & Utility Invoices',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-06-15'),
      workflowHistory: [
        { status: 'Draft', changedBy: plantUser._id, comment: 'Initial reading gathered' },
        { status: 'Submitted', changedBy: plantUser._id, comment: 'Submitted with meter calibration certificates' },
        { status: 'Validated', changedBy: complianceOfficer._id, comment: 'Audited against billing invoices' },
        { status: 'Approved', changedBy: esgManager._id, comment: 'Approved for BRSR Section C reporting' },
      ],
    },
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Electricity Consumption',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: solarBU._id,
      value: 42300,
      unit: 'MWh',
      description: 'Grid electricity consumed for auxiliary substation operations and inverter cooling.',
      dataSource: 'State Grid TOD Invoices',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-06-18'),
    },
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Renewable Energy Generated',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: bhadlaProject._id,
      value: 35000,
      unit: 'MWh',
      description: 'Clean solar PV power generated and fed to interstate transmission network (ISTS).',
      dataSource: 'ISTS Incomer Substation Calibrated Metering',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-20'),
    },
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Renewable Energy Consumed',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: solarBU._id,
      value: 24500,
      unit: 'MWh',
      description: 'Portion of self-generated solar electricity utilized for internal operations.',
      dataSource: 'Internal Auxiliary Metering Log',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-06-21'),
    },
    {
      category: 'Environmental',
      subcategory: 'Water',
      metric: 'Total Water Withdrawal',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 112500,
      unit: 'Kilolitres',
      description: 'Total fresh water withdrawn from municipal and groundwater sources.',
      dataSource: 'Flow Meter Logs & Municipal Water Bills',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-02'),
    },
    {
      category: 'Environmental',
      subcategory: 'Water',
      metric: 'Water Recycled/Reused',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 48900,
      unit: 'Kilolitres',
      description: 'Effluent treated in onsite STP and reused for dust suppression and landscaping.',
      dataSource: 'Onsite STP Flow Monitoring System',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-05'),
    },
    {
      category: 'Environmental',
      subcategory: 'Waste',
      metric: 'Hazardous Waste',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 38,
      unit: 'Metric Tonnes',
      description: 'Spent transformer oil, battery storage cells, and chemical solvent drums disposed via SPCB authorized recyclers.',
      dataSource: 'Manifest Form 10 Hazardous Waste Consignment',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: complianceOfficer._id,
      approvedAt: new Date('2026-07-10'),
    },
    {
      category: 'Environmental',
      subcategory: 'Waste',
      metric: 'Non-Hazardous Waste',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: highwaysBU._id,
      value: 1382,
      unit: 'Metric Tonnes',
      description: 'Construction aggregate, packaging cardboard, and scrap steel.',
      dataSource: 'Weighbridge Manifest Receipts',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-11'),
    },
    {
      category: 'Environmental',
      subcategory: 'Waste',
      metric: 'Waste Recycled',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 960,
      unit: 'Metric Tonnes',
      description: 'Scrap rebar, pavement milling, and plastic packaging diverted from landfills.',
      dataSource: 'Vendor Recycling Certificates',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-12'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'Scope 1 GHG Emissions',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: logisticsSub._id,
      value: 14850,
      unit: 'MT CO2e',
      description: 'Direct combustion emissions from captive heavy diesel fleet and backup gensets.',
      dataSource: 'Fuel log & GHG Protocol emission factors',
      status: 'Approved',
      responsibleUser: createdUsers[3]._id,
      submittedBy: createdUsers[3]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-14'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'Scope 2 GHG Emissions',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 9120,
      unit: 'MT CO2e',
      description: 'Location-based emissions from purchased grid electricity across corporate and site offices.',
      dataSource: 'CEA CO2 Baseline Database v19',
      status: 'Approved',
      responsibleUser: esgManager._id,
      submittedBy: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-15'),
    },
    {
      category: 'Environmental',
      subcategory: 'Incidents',
      metric: 'Environmental Incidents',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 0,
      unit: 'Count',
      description: 'Zero reportable environmental spills, exceedances, or containment breaches.',
      dataSource: 'Group HSE Incident Incident Management Portal',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-15'),
    },
    // Workflow-stage test records (Environmental):
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Fuel Consumption',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: logisticsSub._id,
      value: 16800,
      unit: 'Litres',
      description: 'Diesel fuel consumed by intermodal freight handling equipment.',
      dataSource: 'Monthly Bowser Fuel Slips',
      status: 'Submitted',
      responsibleUser: createdUsers[3]._id,
      submittedBy: createdUsers[3]._id,
      submittedAt: new Date('2026-08-01'),
    },
    {
      category: 'Environmental',
      subcategory: 'Waste',
      metric: 'Total Waste Generated',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: highwaysBU._id,
      value: 1420,
      unit: 'Metric Tonnes',
      description: 'Aggregate debris and industrial packaging from expressways.',
      dataSource: 'Weighbridge logs',
      status: 'Under Review',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      submittedAt: new Date('2026-08-05'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'Scope 3 GHG Emissions',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: freightTerminal._id,
      value: 28400,
      unit: 'MT CO2e',
      description: 'Upstream supply chain freight transport and capital goods emissions.',
      dataSource: 'Subcontractor logistics reports',
      status: 'Correction Required',
      correctionComment: 'Please attach Scope 3 sub-tier carrier emission breakdown and verification memo.',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'NOx Emissions',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: freightTerminal._id,
      value: 38.4,
      unit: 'MT',
      description: 'Nitrogen oxides stack monitoring emission tally.',
      dataSource: 'Online CEMS Stack Analyser',
      status: 'Validated',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      reviewedBy: complianceOfficer._id,
      reviewedAt: new Date('2026-08-10'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'SOx Emissions',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 24.2,
      unit: 'MT',
      description: 'Sulfur dioxide continuous ambient air sampling readings.',
      dataSource: 'Ambient Air Quality Stations (CAAQMS)',
      status: 'Draft',
      responsibleUser: plantUser._id,
    },

    // SOCIAL (2026)
    {
      category: 'Social',
      subcategory: 'Employees',
      metric: 'Total Employees',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 14250,
      unit: 'Nos',
      description: 'Total active workforce across group corporate offices and operational sites.',
      dataSource: 'HRMS Active Payroll Master',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      submittedBy: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Employees',
      metric: 'Permanent Employees',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 9800,
      unit: 'Nos',
      description: 'Permanent full-time on-roll employees.',
      dataSource: 'HRMS Payroll System',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      submittedBy: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Employees',
      metric: 'Contractual Employees',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 4450,
      unit: 'Nos',
      description: 'Contractual site workforce engaged through verified manpower agencies.',
      dataSource: 'Contractor Labour Management System (CLMS)',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-06-26'),
    },
    {
      category: 'Social',
      subcategory: 'Diversity',
      metric: 'Female Employees',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 3620,
      unit: 'Nos',
      description: 'Total female representation across technical, operational, and managerial cadres.',
      dataSource: 'HRMS Diversity Registry',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      submittedBy: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-28'),
    },
    {
      category: 'Social',
      subcategory: 'Diversity',
      metric: 'Women in Leadership',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 28.5,
      unit: '%',
      description: 'Percentage of senior executive and business leadership positions held by women.',
      dataSource: 'HR Leadership Matrix',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      submittedBy: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-28'),
    },
    {
      category: 'Social',
      subcategory: 'Training',
      metric: 'Training Hours',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 56400,
      unit: 'Hours',
      description: 'Total learning and development hours completed on technical, ESG, and safety competencies.',
      dataSource: 'Corporate LMS Portal',
      status: 'Approved',
      responsibleUser: createdUsers[2]._id,
      submittedBy: createdUsers[2]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-01'),
    },
    {
      category: 'Social',
      subcategory: 'Training',
      metric: 'Employees Trained',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 12800,
      unit: 'Nos',
      description: 'Number of individual employees who attended at least one certified training module.',
      dataSource: 'Corporate LMS Records',
      status: 'Approved',
      responsibleUser: esgManager._id,
      submittedBy: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-02'),
    },
    {
      category: 'Social',
      subcategory: 'OHS',
      metric: 'Health & Safety Training Hours',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: bhadlaProject._id,
      value: 22100,
      unit: 'Hours',
      description: 'Electrical isolation, working at heights, and emergency drill safety hours.',
      dataSource: 'HSE Safety Induction Registers',
      status: 'Approved',
      responsibleUser: plantUser._id,
      submittedBy: plantUser._id,
      approvedBy: complianceOfficer._id,
      approvedAt: new Date('2026-07-04'),
    },
    {
      category: 'Social',
      subcategory: 'OHS',
      metric: 'Lost Time Injury Rate',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 0.08,
      unit: 'Rate',
      description: 'LTIR per million person-hours worked across all active construction sites.',
      dataSource: 'Group Safety Incident System',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      submittedBy: createdUsers[4]._id,
      approvedBy: complianceOfficer._id,
      approvedAt: new Date('2026-07-05'),
    },
    {
      category: 'Social',
      subcategory: 'OHS',
      metric: 'Fatalities',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 0,
      unit: 'Count',
      description: 'Zero work-related fatalities achieved across all operations and sites.',
      dataSource: 'Certified Safety Audit Report',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-06'),
    },
    {
      category: 'Social',
      subcategory: 'Welfare',
      metric: 'Employees with Health Insurance',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 100,
      unit: '%',
      description: '100% comprehensive medical cover for all employees and designated dependents.',
      dataSource: 'Group Medical Insurance Policy Master',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      submittedBy: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-07'),
    },
    {
      category: 'Social',
      subcategory: 'Community',
      metric: 'CSR Expenditure',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 52000000,
      unit: 'INR',
      description: 'Statutory Section 135 CSR spend disbursed across rural skill and solar water initiatives.',
      dataSource: 'Audited CSR Financial Ledger',
      status: 'Approved',
      responsibleUser: esgManager._id,
      submittedBy: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-10'),
    },
    {
      category: 'Social',
      subcategory: 'Community',
      metric: 'Community Beneficiaries',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 78000,
      unit: 'People',
      description: 'Villagers benefited through mobile healthcare clinics and solar micro-grids in Kutch and Thar.',
      dataSource: 'Independent CSR Impact Assessment Survey',
      status: 'Approved',
      responsibleUser: createdUsers[2]._id,
      submittedBy: createdUsers[2]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-07-12'),
    },
    {
      category: 'Social',
      subcategory: 'Grievances',
      metric: 'Grievances Received',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 22,
      unit: 'Count',
      description: 'Workplace and community grievances registered during the financial year.',
      dataSource: 'POSH and Internal Complaints Committee Registry',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-15'),
    },
    {
      category: 'Social',
      subcategory: 'Grievances',
      metric: 'Grievances Resolved',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 22,
      unit: 'Count',
      description: '100% resolution of all registered grievances within defined SLA timescales.',
      dataSource: 'Grievance Redressal Committee Minutes',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-15'),
    },

    // GOVERNANCE (2026)
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Total Board Members',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 12,
      unit: 'Nos',
      description: 'Total directors on the board of ESG360 Infra Group Ltd.',
      dataSource: 'MCA Corporate Filing & Secretarial Records',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-10'),
    },
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Independent Directors',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 6,
      unit: 'Nos',
      description: '50% board independence in compliance with SEBI LODR Regulation 17.',
      dataSource: 'Secretarial Audit Report',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-10'),
    },
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Women Directors',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 3,
      unit: 'Nos',
      description: 'Women directors representing 25% of the total board.',
      dataSource: 'Board Composition Profile',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-10'),
    },
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Board Meetings Held',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 7,
      unit: 'Nos',
      description: 'Quarterly and special board meetings conducted with minimum quorum.',
      dataSource: 'Board Meeting Minutes',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-12'),
    },
    {
      category: 'Governance',
      subcategory: 'Ethics',
      metric: 'Ethics Policy Coverage',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 100,
      unit: '%',
      description: 'Comprehensive Code of Conduct signed by 100% of employees, vendors, and partners.',
      dataSource: 'Annual Code of Conduct Acknowledgements',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-15'),
    },
    {
      category: 'Governance',
      subcategory: 'Ethics',
      metric: 'Anti-Corruption Training Completion',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 99.2,
      unit: '%',
      description: 'Completion rate for mandatory annual anti-bribery and anti-corruption modules.',
      dataSource: 'Compliance LMS Tracking',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-16'),
    },
    {
      category: 'Governance',
      subcategory: 'Whistleblower',
      metric: 'Whistleblower Complaints Received',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 5,
      unit: 'Count',
      description: 'Reports submitted via independent ethics hotline portal.',
      dataSource: 'Audit Committee Whistleblower Report',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-20'),
    },
    {
      category: 'Governance',
      subcategory: 'Whistleblower',
      metric: 'Whistleblower Complaints Resolved',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 5,
      unit: 'Count',
      description: 'Independent investigations completed and verified by the Audit Committee.',
      dataSource: 'Audit Committee Resolution Records',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-20'),
    },
    {
      category: 'Governance',
      subcategory: 'Risk',
      metric: 'Identified Material Risks',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 16,
      unit: 'Count',
      description: 'Climate, supply chain, and regulatory risks identified in annual materiality assessment.',
      dataSource: 'Enterprise Risk Management (ERM) Register',
      status: 'Approved',
      responsibleUser: esgManager._id,
      submittedBy: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-22'),
    },
    {
      category: 'Governance',
      subcategory: 'Risk',
      metric: 'Risks with Mitigation Plans',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 16,
      unit: 'Count',
      description: '100% of material risks covered by active mitigation and monitoring frameworks.',
      dataSource: 'ERM Quarterly Review Pack',
      status: 'Approved',
      responsibleUser: esgManager._id,
      submittedBy: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-22'),
    },
    {
      category: 'Governance',
      subcategory: 'Regulatory',
      metric: 'Regulatory Non-Compliances',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 0,
      unit: 'Count',
      description: 'Zero significant regulatory breaches, notices, or sanctions.',
      dataSource: 'Secretarial Audit Certificate',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-25'),
    },
    {
      category: 'Governance',
      subcategory: 'Regulatory',
      metric: 'Regulatory Fines Paid',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 0,
      unit: 'INR',
      description: 'Zero regulatory fines paid across all group entities.',
      dataSource: 'Audited Financial Statements',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-25'),
    },
    {
      category: 'Governance',
      subcategory: 'Data Privacy',
      metric: 'Data Breaches',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 0,
      unit: 'Count',
      description: 'Zero cyber security breaches or personal data compromises.',
      dataSource: 'CISO Annual Information Security Audit',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      submittedBy: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-06-25'),
    },

    // ══════════════════════════════════════════════════════
    // YEAR 2025 (HISTORICAL COMPARISON)
    // ══════════════════════════════════════════════════════
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Total Energy Consumption',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 165000,
      unit: 'GJ',
      status: 'Approved',
      responsibleUser: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2025-06-15'),
    },
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Renewable Energy Generated',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: bhadlaProject._id,
      value: 29500,
      unit: 'MWh',
      status: 'Approved',
      responsibleUser: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2025-06-18'),
    },
    {
      category: 'Environmental',
      subcategory: 'Water',
      metric: 'Total Water Withdrawal',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: urbanInfraSub._id,
      value: 104000,
      unit: 'Kilolitres',
      status: 'Approved',
      responsibleUser: createdUsers[4]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2025-06-20'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'Scope 1 GHG Emissions',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: logisticsSub._id,
      value: 16200,
      unit: 'MT CO2e',
      status: 'Approved',
      responsibleUser: createdUsers[3]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2025-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Employees',
      metric: 'Total Employees',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 13100,
      unit: 'Nos',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2025-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Training',
      metric: 'Training Hours',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 48200,
      unit: 'Hours',
      status: 'Approved',
      responsibleUser: createdUsers[2]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2025-06-28'),
    },
    {
      category: 'Social',
      subcategory: 'Community',
      metric: 'CSR Expenditure',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 46000000,
      unit: 'INR',
      status: 'Approved',
      responsibleUser: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2025-07-02'),
    },
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Total Board Members',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 11,
      unit: 'Nos',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2025-06-10'),
    },
    {
      category: 'Governance',
      subcategory: 'Ethics',
      metric: 'Ethics Policy Coverage',
      reportingPeriod: { year: '2025', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 100,
      unit: '%',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2025-06-12'),
    },

    // ══════════════════════════════════════════════════════
    // YEAR 2024 (HISTORICAL COMPARISON)
    // ══════════════════════════════════════════════════════
    {
      category: 'Environmental',
      subcategory: 'Energy',
      metric: 'Total Energy Consumption',
      reportingPeriod: { year: '2024', quarter: 'Annual' },
      organization: cleanEnergySub._id,
      value: 148000,
      unit: 'GJ',
      status: 'Approved',
      responsibleUser: plantUser._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2024-06-15'),
    },
    {
      category: 'Environmental',
      subcategory: 'Emissions',
      metric: 'Scope 1 GHG Emissions',
      reportingPeriod: { year: '2024', quarter: 'Annual' },
      organization: logisticsSub._id,
      value: 17800,
      unit: 'MT CO2e',
      status: 'Approved',
      responsibleUser: createdUsers[3]._id,
      approvedBy: esgManager._id,
      approvedAt: new Date('2024-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Employees',
      metric: 'Total Employees',
      reportingPeriod: { year: '2024', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 11800,
      unit: 'Nos',
      status: 'Approved',
      responsibleUser: superAdmin._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2024-06-25'),
    },
    {
      category: 'Social',
      subcategory: 'Community',
      metric: 'CSR Expenditure',
      reportingPeriod: { year: '2024', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 39000000,
      unit: 'INR',
      status: 'Approved',
      responsibleUser: esgManager._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2024-07-02'),
    },
    {
      category: 'Governance',
      subcategory: 'Board',
      metric: 'Total Board Members',
      reportingPeriod: { year: '2024', quarter: 'Annual' },
      organization: groupOrg._id,
      value: 10,
      unit: 'Nos',
      status: 'Approved',
      responsibleUser: complianceOfficer._id,
      approvedBy: superAdmin._id,
      approvedAt: new Date('2024-06-10'),
    },
  ];

  const createdESG = await ESGData.insertMany(esgRecords);
  console.log(`✅ Created ${createdESG.length} ESG records across Environmental, Social, and Governance.\n`);

  // 4. CREATE BRSR REPORTS
  console.log('📑 Creating SEBI BRSR Reports...');
  const brsrReports = [
    {
      title: 'SEBI BRSR Comprehensive Annual Report FY 2025-26',
      organization: groupOrg._id,
      reportingPeriod: {
        year: '2026',
        fromDate: new Date('2025-04-01'),
        toDate: new Date('2026-03-31'),
      },
      status: 'In Progress',
      generatedBy: esgManager._id,
      generatedAt: new Date('2026-07-15'),
      overallCompletionPercentage: 86,
      summaryNarrative: 'Comprehensive group disclosures aligned with SEBI BRSR Core Circular covering Energy transition, Scope 1-3 reduction, Zero Fatality safety performance, and board diversity governance.',
      reportVersion: '1.2',
      brsrReference: 'SEBI Circular SEBI/HO/CFD/CFD-SEC-2/P/CIR/2023/122',
      sections: [
        {
          sectionName: 'Section A: General Disclosures',
          isComplete: true,
          completionPercentage: 100,
        },
        {
          sectionName: 'Section B: Management and Process Disclosures',
          isComplete: false,
          completionPercentage: 85,
        },
        {
          sectionName: 'Section C: Principle-wise Performance Disclosures',
          isComplete: false,
          completionPercentage: 78,
        },
      ],
      consolidatedScope: {
        organizations: [cleanEnergySub._id, logisticsSub._id, urbanInfraSub._id],
        includesSubsidiaries: true,
      },
    },
    {
      title: 'SEBI BRSR Statutory Published Filing FY 2024-25',
      organization: groupOrg._id,
      reportingPeriod: {
        year: '2025',
        fromDate: new Date('2024-04-01'),
        toDate: new Date('2025-03-31'),
      },
      status: 'Approved',
      generatedBy: esgManager._id,
      generatedAt: new Date('2025-07-10'),
      approvedBy: superAdmin._id,
      approvedAt: new Date('2025-07-20'),
      overallCompletionPercentage: 100,
      summaryNarrative: 'Statutory filing submitted to National Stock Exchange (NSE) and BSE Limited for FY 2024-25 with independent third-party reasonable assurance.',
      reportVersion: '2.0 Final',
      brsrReference: 'SEBI BRSR 2024 Standard Format',
      sections: [
        { sectionName: 'Section A: General Disclosures', isComplete: true, completionPercentage: 100 },
        { sectionName: 'Section B: Management and Process Disclosures', isComplete: true, completionPercentage: 100 },
        { sectionName: 'Section C: Principle-wise Performance Disclosures', isComplete: true, completionPercentage: 100 },
      ],
    },
    {
      title: 'ESG360 Clean Energy Subsidiary BRSR Section-C Disclosures',
      organization: cleanEnergySub._id,
      reportingPeriod: {
        year: '2026',
        fromDate: new Date('2025-04-01'),
        toDate: new Date('2026-03-31'),
      },
      status: 'Under Review',
      generatedBy: createdUsers[2]._id,
      generatedAt: new Date('2026-08-01'),
      overallCompletionPercentage: 92,
      summaryNarrative: 'Subsidiary-level principle-wise performance metrics for Solar and Wind generation assets.',
      reportVersion: '1.0 Draft',
      brsrReference: 'SEBI BRSR Principle 6 (Environment)',
    },
  ];

  await BRSRReport.insertMany(brsrReports);
  console.log(`✅ Created ${brsrReports.length} BRSR Reports.\n`);

  // 5. CREATE NOTIFICATIONS
  console.log('🔔 Creating Notifications for demo users...');
  const notifications = [
    {
      recipient: superAdmin._id,
      type: 'ESG_APPROVED',
      title: 'ESG Record Approved: Renewable Energy Generated',
      message: 'Bhadla 500MW Ultra Solar Park record has been approved by Group ESG Manager.',
      isRead: false,
      organization: groupOrg._id,
      triggeredBy: esgManager._id,
    },
    {
      recipient: superAdmin._id,
      type: 'ESG_SUBMITTED',
      title: 'New ESG Record Submitted: Fuel Consumption',
      message: 'ESG360 Logistics & Freight Ltd. submitted annual fuel consumption figures for review.',
      isRead: false,
      organization: logisticsSub._id,
      triggeredBy: createdUsers[3]._id,
    },
    {
      recipient: superAdmin._id,
      type: 'CORRECTION_REQUIRED',
      title: 'Correction Flagged: Scope 3 GHG Emissions',
      message: 'Western Freight Hub Scope 3 documentation flagged for carrier sub-tier breakdown verification.',
      isRead: false,
      organization: freightTerminal._id,
      triggeredBy: complianceOfficer._id,
    },
    {
      recipient: superAdmin._id,
      type: 'REPORT_GENERATED',
      title: 'BRSR Report Generated: FY 2025-26',
      message: 'SEBI BRSR Comprehensive Annual Report FY 2025-26 draft is now ready at 86% overall completion.',
      isRead: true,
      organization: groupOrg._id,
      triggeredBy: esgManager._id,
    },
    {
      recipient: superAdmin._id,
      type: 'SYSTEM',
      title: 'SEBI BRSR Core Compliance Check Passed',
      message: 'Automated validation check confirmed all mandatory BRSR Core KPIs are populated for FY 2026.',
      isRead: true,
      organization: groupOrg._id,
    },
  ];

  await Notification.insertMany(notifications);
  console.log(`✅ Created ${notifications.length} Notifications.\n`);

  // 6. CREATE AUDIT LOGS
  console.log('📜 Creating Compliance Audit Logs...');
  const auditLogs = [
    {
      user: superAdmin._id,
      userName: superAdmin.name,
      userEmail: superAdmin.email,
      userRole: superAdmin.role,
      password: ADMIN_PASSWORD,
      action: 'LOGIN',
      entity: 'User',
      entityId: superAdmin._id,
      organization: groupOrg._id,
      organizationName: groupOrg.name,
      status: 'Success',
      createdAt: new Date('2026-08-20T09:15:00Z'),
    },
    {
      user: plantUser._id,
      userName: plantUser.name,
      userEmail: plantUser.email,
      userRole: plantUser.role,
      password: ADMIN_PASSWORD,
      action: 'CREATE',
      entity: 'ESGData',
      organization: bhadlaProject._id,
      organizationName: bhadlaProject.name,
      status: 'Success',
      createdAt: new Date('2026-08-20T10:00:00Z'),
    },
    {
      user: plantUser._id,
      userName: plantUser.name,
      userEmail: plantUser.email,
      userRole: plantUser.role,
      password: ADMIN_PASSWORD,
      action: 'SUBMIT',
      entity: 'ESGData',
      organization: bhadlaProject._id,
      organizationName: bhadlaProject.name,
      status: 'Success',
      createdAt: new Date('2026-08-20T10:15:00Z'),
    },
    {
      user: complianceOfficer._id,
      userName: complianceOfficer.name,
      userEmail: complianceOfficer.email,
      userRole: complianceOfficer.role,
      password: ADMIN_PASSWORD,
      action: 'VALIDATE',
      entity: 'ESGData',
      organization: groupOrg._id,
      organizationName: groupOrg.name,
      status: 'Success',
      createdAt: new Date('2026-08-20T11:30:00Z'),
    },
    {
      user: esgManager._id,
      userName: esgManager.name,
      userEmail: esgManager.email,
      userRole: esgManager.role,
      password: ADMIN_PASSWORD,
      action: 'APPROVE',
      entity: 'ESGData',
      organization: groupOrg._id,
      organizationName: groupOrg.name,
      status: 'Success',
      createdAt: new Date('2026-08-20T14:00:00Z'),
    },
    {
      user: esgManager._id,
      userName: esgManager.name,
      userEmail: esgManager.email,
      userRole: esgManager.role,
      password: ADMIN_PASSWORD,
      action: 'REPORT_GENERATE',
      entity: 'BRSRReport',
      organization: groupOrg._id,
      organizationName: groupOrg.name,
      status: 'Success',
      createdAt: new Date('2026-08-21T09:00:00Z'),
    },
    {
      user: superAdmin._id,
      userName: superAdmin.name,
      userEmail: superAdmin.email,
      userRole: superAdmin.role,
      password: ADMIN_PASSWORD,
      action: 'CONSOLIDATE',
      entity: 'Organization',
      organization: groupOrg._id,
      organizationName: groupOrg.name,
      status: 'Success',
      createdAt: new Date('2026-08-21T11:00:00Z'),
    },
  ];

  await AuditLog.insertMany(auditLogs);
  console.log(`✅ Created ${auditLogs.length} Compliance Audit Logs.\n`);

  // 6. CREATE DUMMY COMPLIANCE DOCUMENTS
  console.log('📄 Creating Dummy Compliance & Evidence Documents across Organizations...');
  const dummyDocs = [
    {
      originalName: 'ESG360_Group_Annual_Audit_Assurance_FY25-26.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/group/audit_assurance_fy25_26',
      fileType: 'application/pdf',
      fileSize: 3450000,
      category: 'Audit Report',
      organization: groupOrg._id,
      uploadedBy: auditorUser._id,
      description: 'Independent limited assurance report conducted by external audit firm covering BRSR core indicators.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-08-15T10:00:00Z'),
      reviewComment: 'Verified against SEBI BRSR standard core indicators. Fully assured.',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['Audit', 'External Assurance', 'BRSR', 'FY26'],
    },
    {
      originalName: 'ESG360_Corporate_Environmental_Climate_Policy_2026.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/group/env_policy_2026',
      fileType: 'application/pdf',
      fileSize: 1820000,
      category: 'Policy Document',
      organization: groupOrg._id,
      uploadedBy: groupAdmin._id,
      description: 'Board-approved corporate policy framework for greenhouse gas reduction, net-zero roadmap, and water security.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-01-10T11:30:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['Policy', 'Climate', 'Net-Zero', 'Governance'],
    },
    {
      originalName: 'Board_Diversity_Human_Rights_Policy_Declaration.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/group/board_diversity_2026',
      fileType: 'application/pdf',
      fileSize: 940000,
      category: 'Board Document',
      organization: groupOrg._id,
      uploadedBy: complianceOfficer._id,
      description: 'Charter of the ESG Nomination and Governance Committee outlining board gender ratio and supplier human rights code.',
      status: 'Validated',
      reviewedBy: auditorUser._id,
      reviewedAt: new Date('2026-07-12T14:15:00Z'),
      reviewComment: 'Methodology and board resolutions validated.',
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['Board', 'Diversity', 'Human Rights'],
    },
    {
      originalName: 'Consolidated_Group_Energy_Emissions_Evidence_FY25.xlsx',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/raw/upload/v1690000000/sample.xlsx',
      cloudinaryPublicId: 'esg360/group/energy_evidence_fy25',
      fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      fileSize: 2480000,
      category: 'ESG Evidence',
      organization: groupOrg._id,
      uploadedBy: esgManager._id,
      description: 'Aggregated utility bills, sub-meter readings, and fuel procurement receipts across all operational subsidiaries.',
      status: 'Under Review',
      reviewedBy: groupAdmin._id,
      reviewedAt: new Date('2026-09-18T09:45:00Z'),
      reviewComment: 'Currently verifying Scope 2 grid emission factors against Central Electricity Authority baseline database.',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['Scope 1', 'Scope 2', 'Utility Bills', 'Energy'],
    },
    {
      originalName: 'Bhadla_Solar_Phase_IV_Environmental_Clearance_MOEFCC.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/clean_energy/moefcc_clearance',
      fileType: 'application/pdf',
      fileSize: 4200000,
      category: 'Environmental Certificate',
      organization: cleanEnergySub._id,
      uploadedBy: energySubAdmin._id,
      description: 'Statutory Environmental Clearance issued by Ministry of Environment, Forest and Climate Change for 300MW solar installation.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-03-22T16:00:00Z'),
      reviewComment: 'Statutory compliance confirmed.',
      reportingPeriod: { year: '2026', quarter: 'Q1' },
      tags: ['Statutory', 'MOEFCC', 'Solar', 'Compliance'],
    },
    {
      originalName: 'Clean_Energy_ISO_14001_Environment_Management_Certificate.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/clean_energy/iso_14001',
      fileType: 'application/pdf',
      fileSize: 1560000,
      category: 'Environmental Certificate',
      organization: cleanEnergySub._id,
      uploadedBy: energySubAdmin._id,
      description: 'TUV Rheinland ISO 14001:2015 environmental management systems certification valid through 2028.',
      status: 'Approved',
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-04-10T12:00:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['ISO 14001', 'EMS', 'Certification'],
    },
    {
      originalName: 'Solar_Park_Contractor_EHS_Monthly_Safety_Log.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/clean_energy/ehs_safety_log',
      fileType: 'application/pdf',
      fileSize: 820000,
      category: 'Safety Record',
      organization: cleanEnergySub._id,
      uploadedBy: energySubAdmin._id,
      description: 'Zero Lost Time Injury logbook and toolbox talk attendance sheets for solar plant contract workers.',
      status: 'Validated',
      reviewedBy: complianceOfficer._id,
      reviewedAt: new Date('2026-08-01T15:20:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['Safety', 'EHS', 'Zero Harm', 'LTI'],
    },
    {
      originalName: 'Clean_Energy_Green_Credits_CERC_Tariff_Statement.xlsx',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/raw/upload/v1690000000/sample.xlsx',
      cloudinaryPublicId: 'esg360/clean_energy/green_credits',
      fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      fileSize: 1120000,
      category: 'Financial Data',
      organization: cleanEnergySub._id,
      uploadedBy: esgManager._id,
      description: 'Renewable energy certificates issuance statement and clean power purchase agreements revenues.',
      status: 'Under Review',
      reviewedBy: auditorUser._id,
      reviewedAt: new Date('2026-09-10T11:00:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Q3' },
      tags: ['Finance', 'REC', 'Carbon Credits'],
    },
    {
      originalName: 'Electric_Fleet_EV_Telematics_Log_Q2_2026.xlsx',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/raw/upload/v1690000000/sample.xlsx',
      cloudinaryPublicId: 'esg360/logistics/ev_fleet_telematics',
      fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      fileSize: 2890000,
      category: 'ESG Evidence',
      organization: logisticsSub._id,
      uploadedBy: logisticsSubAdmin._id,
      description: 'Automated telematics data measuring diesel displacement by 120 heavy electric freight haulers.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-07-28T14:40:00Z'),
      reviewComment: 'Verified with GPS telemetry records. Fuel reduction numbers cross-matched.',
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['Logistics', 'EV Fleet', 'Diesel Displacement', 'Scope 1'],
    },
    {
      originalName: 'Port_Terminals_Hazardous_Waste_Discharge_Consent.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/logistics/hazardous_waste_consent',
      fileType: 'application/pdf',
      fileSize: 1650000,
      category: 'Environmental Certificate',
      organization: logisticsSub._id,
      uploadedBy: complianceOfficer._id,
      description: 'State Pollution Control Board Consent to Operate for port bunkering and bilge oil separation units.',
      status: 'Validated',
      reviewedBy: auditorUser._id,
      reviewedAt: new Date('2026-06-19T10:15:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['Pollution Board', 'CTO', 'Hazardous Waste', 'Water'],
    },
    {
      originalName: 'Driver_Fatigue_Incident_Investigation_Report.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/logistics/safety_correction',
      fileType: 'application/pdf',
      fileSize: 740000,
      category: 'Safety Record',
      organization: logisticsSub._id,
      uploadedBy: logisticsSubAdmin._id,
      description: 'Root cause analysis of NH-48 minor transport collision and driver shift rotation schedule.',
      status: 'Correction Required',
      correctionComment: 'Shift schedule in Appendix B is missing driver rest time logs. Please attach biometric sign-off records.',
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['Safety', 'Incident', 'Correction Required'],
    },
    {
      originalName: 'Metro_Line_3_Urban_Biodiversity_Impact_Assessment.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/urban_infra/biodiversity_report',
      fileType: 'application/pdf',
      fileSize: 3100000,
      category: 'ESG Evidence',
      organization: urbanInfraSub._id,
      uploadedBy: urbanSubAdmin._id,
      description: 'Comprehensive ecological study covering compensatory afforestation of 25,000 native tree saplings.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-05-14T09:30:00Z'),
      reviewComment: 'Geo-tagged afforestation records approved.',
      reportingPeriod: { year: '2026', quarter: 'Annual' },
      tags: ['Biodiversity', 'Afforestation', 'Metro Infrastructure'],
    },
    {
      originalName: 'Precast_Yard_Rainwater_Harvesting_Zero_Discharge_Cert.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/urban_infra/water_recycle_cert',
      fileType: 'application/pdf',
      fileSize: 1250000,
      category: 'Environmental Certificate',
      organization: urbanInfraSub._id,
      uploadedBy: urbanSubAdmin._id,
      description: 'Third-party hydrological certification for 100% wastewater recycling and artificial aquifer recharge pit.',
      status: 'Approved',
      approvedBy: esgManager._id,
      approvedAt: new Date('2026-06-30T17:00:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['Water', 'Rainwater Harvesting', 'Zero Discharge'],
    },
    {
      originalName: 'Bhadla_Solar_Pyranometer_Solar_Irradiance_Calibration.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/solar_bu/pyranometer_cert',
      fileType: 'application/pdf',
      fileSize: 670000,
      category: 'ESG Evidence',
      organization: solarBU._id,
      uploadedBy: buManager._id,
      description: 'NABL accredited laboratory calibration report for solar irradiance sensors and energy yield audit.',
      status: 'Approved',
      approvedBy: superAdmin._id,
      approvedAt: new Date('2026-04-18T10:00:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Q1' },
      tags: ['Solar BU', 'Calibration', 'Energy Yield'],
    },
    {
      originalName: 'Substation_High_Voltage_Switchgear_SF6_Gas_Leakage_Log.pdf',
      cloudinaryUrl: 'https://res.cloudinary.com/demo/image/upload/v1690000000/sample.pdf',
      cloudinaryPublicId: 'esg360/solar_bu/sf6_leakage_audit',
      fileType: 'application/pdf',
      fileSize: 890000,
      category: 'Environmental Certificate',
      organization: solarBU._id,
      uploadedBy: buManager._id,
      description: 'Zero SF6 greenhouse gas leakage verification test for 400kV step-up substation.',
      status: 'Approved',
      approvedBy: groupAdmin._id,
      approvedAt: new Date('2026-05-25T14:30:00Z'),
      reportingPeriod: { year: '2026', quarter: 'Q2' },
      tags: ['SF6', 'GHG', 'Substation', 'Environmental'],
    },
  ];

  await Document.insertMany(dummyDocs);
  console.log(`✅ Created ${dummyDocs.length} Compliance & Evidence Documents.\n`);

  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('🎉 SEED COMPLETED SUCCESSFULLY!');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📌 Login Credentials (All users share password: ' + ADMIN_PASSWORD + ')');
  console.log('   Super Admin         : admin@esg360.com');
  console.log('   Group ESG Admin     : group.admin@esg360.com');
  console.log('   Subsidiary Admin    : energy.sub@esg360.com');
  console.log('   BU Manager          : solar.bu@esg360.com');
  console.log('   Plant Data User     : bhadla.user@esg360.com');
  console.log('   ESG Manager         : esg.manager@esg360.com');
  console.log('   Compliance Officer  : compliance@esg360.com');
  console.log('   Auditor/Reviewer    : auditor@esg360.com');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
