"""resume uploads

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 10:45:10.752374
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_uploads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('stored_path', sa.String(length=400), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_uploads_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_uploads_student_id'))

    op.drop_table('resume_uploads')
    # ### end Alembic commands ###
